<?php

/**
 * @file
 * Contains event_dispatcher_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eventdispatcherexample_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_dispatcher_example module.
    case 'help.page.event_dispatcher_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal8 Symfony event dispatcher example') . '</p>';
      return $output;

    default:
  }
}
